server:
  port: 9527

spring:
  application:
    name: springcloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: payment_routh  #路由ID 没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://SPRINGCLOUD-PAYMENT-SERVICE #匹配服务器提供的地址 前面lb://前缀是负载均衡的意思
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://SPRINGCLOUD-PAYMENT-SERVICE #匹配服务器提供的地址
          predicates:
            - Path=/payment/lb/**
            - After=2020-07-24T03:53:31.674+08:00[Asia/Shanghai] #断言After意思为在此时间之后访问上述路径才能生效
            #- Cookie=username,harman #限定cookie名称为harman的 cmd输入 curl http://localhost:9527/payment/lb --cookie "username=harman"
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb -H "X-Request-Id:1234"
            #- Method=Get
            #- Query=username, \d+ #要有参数名username并且值还要是整数才能路由 curl http://localhost:9527/payment/lb?username=123
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加上一对请求头，名称为X-Request-Id值为1024
eureka:
  instance:
    hostname: springcloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka