server:
  port: 3344

spring:
  application:
    name: springcloud-config-center

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Harman-pepsi/springcloud-config.git #Github上面的git仓库名字
          username: 853696509@qq.com
          password: 1314Xujinchuan
          search-paths:
            - springcloud-config
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
