server:
  port: 8003

spring:
  application:
    name: springcloud-provider-payment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=GMT%2B8
    username: root
    password: 123456


  cloud:
    zookeeper:
      connect-string: 192.168.0.105:2181

mybatis:
  type-aliases-package: cn.demo.entry
  mapper-locations: classpath:mapper/*.xml
