server:
  port: 8801

spring:
  application:
    name: springcloud-stream-provider

  cloud:
    stream:
      binders: #此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binging整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.0.105
                port: 5672
                username: admin
                password: admin
      bindings: #服务整合的处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为json，文本则设置为text/plain
          default-binder: defaultRabbit #设置要绑定的消息服务的具体设置
          grop: groupA #同组竞争，异组重复接受
eureka:
  client:
    service-url:
      defualtZone: http://eureka7001.com:7001/eureka

  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔
    lease-expiration-duration-in-seconds: 5 #如果超出5秒时间间隔
    instance-id: receive-8802.com #在信息列表时显示主机名称
    prefer-ip-address: true #访问路径变为ip地址
